# Generated by Django 4.1.5 on 2025-10-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=10)),
                ('brand_name', models.CharField(max_length=20)),
                ('original_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('image_url', models.CharField(max_length=500)),
                ('rank', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
