# Generated by Django 5.2.6 on 2025-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutriscopedata',
            name='total_rank',
        ),
        migrations.AlterField(
            model_name='nutriscopedata',
            name='brand_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutriscopedata',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='nutriscopedata',
            name='display_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='nutriscopedata',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutriscopedata',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nutriscopedata',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutriscopedata',
            name='shop_name',
            field=models.CharField(max_length=50),
        ),
    ]
