# Generated by Django 5.2.6 on 2025-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_nutriscopedata_total_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutriscopedata',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutriscopedata',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nutriscopedata',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
