# Generated by Django 5.2.6 on 2025-10-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_nutriscopedata_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriscopedata',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
