# Generated by Django 5.2.6 on 2025-10-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_nutriscopedata_representative_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriscopedata',
            name='total_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
